<a href="https://colab.research.google.com/github/LeylahfrA01178568/2039_data_visualization/blob/main/Activity_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring the Cartwheel dataset

In [5]:
file_path = 'https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/Cartwheeldata.csv'
import pandas as pd
df = pd.read_csv(file_path)
df.head(2)

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56,F,1,Y,1,62.0,61.0,79,Y,1,7
1,2,26,F,1,Y,1,62.0,60.0,70,Y,1,8



1.   What data did we receive?
2.   How do we inspect exactly rows and columns we need?
3.   What categories exists?
4.   Are some variables redundant?

## Data we receive

- `Age` is a numerical variable

In [6]:
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [7]:
df.GenderGroup.unique()

array([1, 2])

Gender Group and Gender are redundant 1= Female & 2 = Male ( GenderGroup is a categorical variable)

In [8]:
df.shape

(25, 12)

25 rows and 12 columns

In [11]:
df.shape[0]

25

In [14]:
print('There are ', df.shape[0], 'columns')
print('There are ', df.shape[1], 'rows')

There are  25 columns
There are  12 rows

In [16]:
print(*df.columns, sep='\n')

ID
Age
Gender
GenderGroup
Glasses
GlassesGroup
Height
Wingspan
CWDistance
Complete
CompleteGroup
Score

In [17]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [20]:
favs_col = ['Age','Gender','Glasses','Height', 'Wingspan','CWDistance', 'Complete','Score'] #now select favorite columns ( non redundant) into a list
favs_col

['Age',
 'Gender',
 'Glasses',
 'Height',
 'Wingspan',
 'CWDistance',
 'Complete',
 'Score']

In [21]:
type(favs_col)

list

In [23]:
ndf = df[favs_col]
ndf.head(2)

   Age Gender Glasses  Height  Wingspan  CWDistance Complete  Score
0   56      F       Y    62.0      61.0          79        Y      7
1   26      F       Y    62.0      60.0          70        Y      8

In [26]:
ndf.dtypes

Age             int64
Gender         object
Glasses        object
Height        float64
Wingspan      float64
CWDistance      int64
Complete       object
Score           int64
dtype: object

int64 is integer

groups is text

float64 is float

In [28]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         25 non-null     int64
 1   Gender      25 non-null     object
 2   Glasses     25 non-null     object
 3   Height      25 non-null     float64
 4   Wingspan    25 non-null     float64
 5   CWDistance  25 non-null     int64
 6   Complete    25 non-null     object
 7   Score       25 non-null     int64
dtypes: float64(2), int64(3), object(3)
memory usage: 1.7+ KB

In [29]:
ndf.describe()

             Age     Height   Wingspan  CWDistance      Score
count  25.000000  25.000000  25.000000   25.000000  25.000000
mean   28.240000  67.650000  66.260000   82.480000   6.120000
std     6.989754   4.431187   5.492647   15.058552   2.833137
min    22.000000  61.500000  57.500000   63.000000   0.000000
25%    24.000000  64.000000  62.000000   70.000000   4.000000
50%    26.000000  68.000000  66.000000   81.000000   6.000000
75%    29.000000  71.000000  71.000000   92.000000   8.000000
max    56.000000  75.000000  76.000000  115.000000  10.000000

In [31]:
ndf.Age.min()

22

In [35]:
print('Age min ', ndf.Age.min())
print('Age max ', ndf.Age.max())
print('Age mean ', ndf.Age.mean())
print('Age median ', ndf.Age.median())
print('Age std ', ndf.Age.std())

Age min  22
Age max  56
Age mean  28.24
Age median  26.0
Age std  6.98975440674897

## How do we inspect exactly the rows and columns we need?

loc & iloc

df.loc[row_start_name: row_end_name, col_start_name: col_end_name]

df.iloc[row_start_int: row_end_int, col_start_int: col_end_int]

In [36]:
ndf.columns

Index(['Age', 'Gender', 'Glasses', 'Height', 'Wingspan', 'CWDistance',
       'Complete', 'Score'],
      dtype='object')

### 2.1 CHoose first 4 columns

In [39]:
ndf.loc[ :  , :'Height'] # write the name of the 4 column

    Age Gender Glasses  Height
0    56      F       Y   62.00
1    26      F       Y   62.00
2    33      F       Y   66.00
3    39      F       N   64.00
4    27      M       N   73.00
5    24      M       N   75.00
6    28      M       N   75.00
7    22      F       N   65.00
8    29      M       Y   74.00
9    33      F       Y   63.00
10   30      M       Y   69.50
11   28      F       Y   62.75
12   25      F       Y   65.00
13   23      F       N   61.50
14   31      M       Y   73.00
15   26      M       Y   71.00
16   26      F       N   61.50
17   27      M       N   66.00
18   23      M       Y   70.00
19   24      F       Y   68.00
20   23      M       Y   69.00
21   29      M       N   71.00
22   25      M       N   70.00
23   26      M       N   69.00
24   23      F       Y   65.00

In [41]:
ndf.iloc[:,:4]

    Age Gender Glasses  Height
0    56      F       Y   62.00
1    26      F       Y   62.00
2    33      F       Y   66.00
3    39      F       N   64.00
4    27      M       N   73.00
5    24      M       N   75.00
6    28      M       N   75.00
7    22      F       N   65.00
8    29      M       Y   74.00
9    33      F       Y   63.00
10   30      M       Y   69.50
11   28      F       Y   62.75
12   25      F       Y   65.00
13   23      F       N   61.50
14   31      M       Y   73.00
15   26      M       Y   71.00
16   26      F       N   61.50
17   27      M       N   66.00
18   23      M       Y   70.00
19   24      F       Y   68.00
20   23      M       Y   69.00
21   29      M       N   71.00
22   25      M       N   70.00
23   26      M       N   69.00
24   23      F       Y   65.00

### 2.2 CHoose the specific cols `'Age', 'Gender', 'Height', 'CWDistance',`

In [72]:
favs_word = ['Age', 'Gender', 'Height', 'CWDistance']
favs_word

['Age', 'Gender', 'Height', 'CWDistance']

In [73]:
ndf.loc[:, favs_word]

    Age Gender  Height  CWDistance
0    56      F   62.00          79
1    26      F   62.00          70
2    33      F   66.00          85
3    39      F   64.00          87
4    27      M   73.00          72
5    24      M   75.00          81
6    28      M   75.00         107
7    22      F   65.00          98
8    29      M   74.00         106
9    33      F   63.00          65
10   30      M   69.50          96
11   28      F   62.75          79
12   25      F   65.00          92
13   23      F   61.50          66
14   31      M   73.00          72
15   26      M   71.00         115
16   26      F   61.50          90
17   27      M   66.00          74
18   23      M   70.00          64
19   24      F   68.00          85
20   23      M   69.00          66
21   29      M   71.00         101
22   25      M   70.00          82
23   26      M   69.00          63
24   23      F   65.00          67

In [49]:
favs_in= [0,1,3,5]
ndf.iloc[:,favs_in]

    Age Gender  Height  CWDistance
0    56      F   62.00          79
1    26      F   62.00          70
2    33      F   66.00          85
3    39      F   64.00          87
4    27      M   73.00          72
5    24      M   75.00          81
6    28      M   75.00         107
7    22      F   65.00          98
8    29      M   74.00         106
9    33      F   63.00          65
10   30      M   69.50          96
11   28      F   62.75          79
12   25      F   65.00          92
13   23      F   61.50          66
14   31      M   73.00          72
15   26      M   71.00         115
16   26      F   61.50          90
17   27      M   66.00          74
18   23      M   70.00          64
19   24      F   68.00          85
20   23      M   69.00          66
21   29      M   71.00         101
22   25      M   70.00          82
23   26      M   69.00          63
24   23      F   65.00          67

### 2.3 Same fav columns, but with
- **2.3.1** top 5 rows
- **2.3.2**  top 5 lower rows
- **2.3.2**  rows 5-10

#### 2.3.1 top 5 rows

In [74]:
ndf.loc[:4, favs_word]

   Age Gender  Height  CWDistance
0   56      F    62.0          79
1   26      F    62.0          70
2   33      F    66.0          85
3   39      F    64.0          87
4   27      M    73.0          72

In [63]:
ndf.iloc[:5,favs_in]

   Age Gender  Height  CWDistance
0   56      F    62.0          79
1   26      F    62.0          70
2   33      F    66.0          85
3   39      F    64.0          87
4   27      M    73.0          72

#### 2.3.2 bottom 5 rows

In [68]:
ndf.shape

(25, 8)

In [69]:
ndf.loc[20:, favs_n]

    Age Gender  Height  CWDistance
20   23      M    69.0          66
21   29      M    71.0         101
22   25      M    70.0          82
23   26      M    69.0          63
24   23      F    65.0          67

In [70]:
ndf.iloc[-5:,favs_in]

    Age Gender  Height  CWDistance
20   23      M    69.0          66
21   29      M    71.0         101
22   25      M    70.0          82
23   26      M    69.0          63
24   23      F    65.0          67

### 2.3.3 Rows 5-10

Iloc is you want to see the actual number 5 of the row, when its actually row 6

In [76]:
ndf.iloc[5:11,favs_in]

    Age Gender  Height  CWDistance
5    24      M    75.0          81
6    28      M    75.0         107
7    22      F    65.0          98
8    29      M    74.0         106
9    33      F    63.0          65
10   30      M    69.5          96

In [78]:
ndf.loc[5:10, favs_word]

    Age Gender  Height  CWDistance
5    24      M    75.0          81
6    28      M    75.0         107
7    22      F    65.0          98
8    29      M    74.0         106
9    33      F    63.0          65
10   30      M    69.5          96

## 3. What Catehories exist? in our original data set?

In [79]:
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56,F,1,Y,1,62.0,61.0,79,Y,1,7
1,2,26,F,1,Y,1,62.0,60.0,70,Y,1,8
2,3,33,F,1,Y,1,66.0,64.0,85,Y,1,0
3,4,39,F,1,N,0,64.0,63.0,87,Y,1,10
4,5,27,M,2,N,0,73.0,75.0,72,N,0,4

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             25 non-null     int64
 1   Age            25 non-null     int64
 2   Gender         25 non-null     object
 3   GenderGroup    25 non-null     int64
 4   Glasses        25 non-null     object
 5   GlassesGroup   25 non-null     int64
 6   Height         25 non-null     float64
 7   Wingspan       25 non-null     float64
 8   CWDistance     25 non-null     int64
 9   Complete       25 non-null     object
 10  CompleteGroup  25 non-null     int64
 11  Score          25 non-null     int64
dtypes: float64(2), int64(7), object(3)
memory usage: 2.5+ KB

In [83]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [85]:
df.Gender.unique()

array(['F', 'M'], dtype=object)

1. `'Gender'` : Explains Gender of each participant, categories are  [ F, M]
2. `GenderGroup` :  Also categorical variable, but it shows numerical categories [1, 2]. We have to convert this to categorical variable.
 , ç, 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'

In [89]:
df.GenderGroup[0]

np.int64(1)

In [93]:
df['GenderGroup'] = df.GenderGroup.astype('str')
df.GenderGroup[0]

'1'

In [95]:
df.iloc[:,2:4]

   Gender GenderGroup
0       F           1
1       F           1
2       F           1
3       F           1
4       M           2
5       M           2
6       M           2
7       F           1
8       M           2
9       F           1
10      M           2
11      F           1
12      F           1
13      F           1
14      M           2
15      M           2
16      F           1
17      M           2
18      M           2
19      F           1
20      M           2
21      M           2
22      M           2
23      M           2
24      F           1

In [99]:
favs_gen = ['Gender','GenderGroup', 'Glasses']
df[favs_gen].value_counts()

Gender  GenderGroup  Glasses
F       1            Y          8
M       2            N          7
                     Y          6
F       1            N          4
Name: count, dtype: int64

In [100]:
df.groupby(['Gender','GenderGroup']).size()

Gender  GenderGroup
F       1              12
M       2              13
dtype: int64

In [ ]:
y

# Aiustralianwines

In [116]:
path2= 'https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/AustralianWines.csv'

In [117]:
import pandas as pd
df2 = pd.read_csv(path2)

 ## Rows And Columns

In [118]:
df2.head()

    Month Fortified  Red  Rose   sparkling   Sweet white  Dry white
0  Jan-80      2585   464   112      1686.0         85.0     1954.0
1  Feb-80      3368   675   118      1591.0         89.0     2302.0
2  Mar-80      3210   703   129      2304.0        109.0     3054.0
3  Apr-80      3111   887    99      1712.0         95.0     2414.0
4  May-80      3756  1139   116      1471.0         91.0     2226.0

In [119]:
df2.shape

(188, 7)

In [120]:
print(' Australian Wines files has ', df2.shape[0], 'rows')
print(' Australian Wines files has ', df2.shape[1], 'columns')

 Australian Wines files has  188 rows
 Australian Wines files has  7 columns

## Read Red ,Rose & Sparkling  rows 10-19

In [136]:
Columns_fav_in = df2.iloc[:,2:5]
Columns_fav_in

     Red  Rose   sparkling
0     464   112      1686.0
1     675   118      1591.0
2     703   129      2304.0
3     887    99      1712.0
4    1139   116      1471.0
..    ...   ...         ...
183   NaN   NaN         NaN
184   NaN   NaN         NaN
185   NaN   NaN         NaN
186   NaN   NaN         NaN
187         NaN         NaN

[188 rows x 3 columns]

In [137]:
Rows_favs_in =df2.iloc[10:20,:]
Rows_favs_in

     Month Fortified  Red  Rose   sparkling   Sweet white  Dry white
10  Nov-80      3661   996   150      4087.0        178.0     4009.0
11  Dec-80      3795   960   267      5179.0        140.0     3924.0
12  Jan-81      2285   530   126      1530.0        150.0     2072.0
13  Feb-81      2934   883   129      1523.0        132.0     2434.0
14  Mar-81      2985   894   124      1633.0        155.0     2956.0
15  Apr-81      3646  1045    97      1976.0        132.0     2828.0
16  May-81      4198  1199   102      1170.0         91.0     2687.0
17  Jun-81      4935  1287   127      1480.0         94.0     2629.0
18  Jul-81      5618  1565   222      1781.0        109.0     3150.0
19  Aug-81      5454  1577   214      2472.0        155.0     4119.0

In [138]:
df2.iloc[10:20,2:5]

    Red  Rose   sparkling
10   996   150      4087.0
11   960   267      5179.0
12   530   126      1530.0
13   883   129      1523.0
14   894   124      1633.0
15  1045    97      1976.0
16  1199   102      1170.0
17  1287   127      1480.0
18  1565   222      1781.0
19  1577   214      2472.0