<a href="https://colab.research.google.com/github/LeylahfrA01178568/2039_data_visualization/blob/main/clean_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd
import numpy as np

In [112]:
x = {
    'Company': ['Ford', 'Ford','VM', 'BMW', 'Cooper', 'Cooper'],
    'Stars' : [1, 2, np.nan, 2, 1,1],
    'Weight': [2, 4, 4, 2, 3, None],
    'Origin': ['China', 'Mexico', 'Mexico', None, 'China', np.nan],
    'Length': [40, 50, 30, np.nan, 45, pd.NaT]
}
df = pd.DataFrame(data = x)
df.head(2)

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50

In [113]:
df.isnull()

   Company  Stars  Weight  Origin  Length
0    False  False   False   False   False
1    False  False   False   False   False
2    False   True   False   False   False
3    False  False   False    True    True
4    False  False   False   False   False
5    False  False    True    True    True

True means there is missing data

In [114]:
df.isnull().any() # which column

Company    False
Stars       True
Weight      True
Origin      True
Length      True
dtype: bool

In [115]:
df.isnull().any(axis = 1) # which is row

0    False
1    False
2     True
3     True
4    False
5     True
dtype: bool

### 1. Drop the rows, if there is at least one missing value

In [116]:
ndf1 = df.copy() # don't modify original data
ndf1.head()

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VM    NaN     4.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45

In [117]:
ndf1 = ndf1.dropna() # all the raws with at least one missing value # also ndf1.dropna(inplace=True)

In [118]:
ndf1

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
4  Cooper    1.0     3.0   China     45

In [119]:
ndf1.isnull().any().sum()

np.int64(0)

### 2. Drop the columns, if there is at least one missing value

In [120]:
ndf2 = df.copy()

In [121]:
ndf2 = ndf2.dropna(axis = 1)

In [122]:
ndf2

  Company
0    Ford
1    Ford
2      VM
3     BMW
4  Cooper
5  Cooper

In [123]:
ndf2.isnull().any().sum()

np.int64(0)

### 3. Drop all the rows, if all the values are missing

In [124]:
x3 = {
    'Company': ['Ford', 'Ford','VM', 'BMW', 'Cooper', 'Cooper', None],
    'Stars' : [1, 2, np.nan, 2, 1,1, None],
    'Weight': [2, 4, 4, 2, 3, None, None],
    'Origin': ['China', 'Mexico', 'Mexico', None, 'China', np.nan, None],
    'Length': [40, 50, 30, np.nan, 45, pd.NaT, None]
}
df3 = pd.DataFrame(data = x3)
df3.head(2)

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50

In [125]:
ndf3 = df3.copy()

In [126]:
ndf3 = ndf3.dropna(how = 'all') #if the ending row is missing eliminate it
ndf3

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VM    NaN     4.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

### 4. Drop those columns, if the entire dara is missing.

In [127]:
x4 = {
    'Company': ['Ford', 'Ford','VM', 'BMW', 'Cooper', 'Cooper'],
    'Stars' : [1, 2, np.nan, 2, 1,1],
    'Weight': [2, 4, 4, 2, 3, None],
    'Origin': ['China', 'Mexico', 'Mexico', None, 'China', np.nan],
    'Length': [40, 50, 30, np.nan, 45, pd.NaT],
    'Nones':[None, None, None, None, None, None],
}
df4 = pd.DataFrame(data = x4)
df4.head(2)

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     4.0  Mexico     50  None

In [128]:
ndf4 =df4.copy()

In [129]:
ndf4 = ndf4.dropna(how = 'all', axis = 1)
ndf4

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VM    NaN     4.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     NaN     NaN    NaT

In [130]:
df4.shape

(6, 6)

In [131]:
df4

  Company  Stars  Weight  Origin Length Nones
0    Ford    1.0     2.0   China     40  None
1    Ford    2.0     4.0  Mexico     50  None
2      VM    NaN     4.0  Mexico     30  None
3     BMW    2.0     2.0    None    NaN  None
4  Cooper    1.0     3.0   China     45  None
5  Cooper    1.0     NaN     NaN    NaT  None

### 5. If there are at least 4 values per row, `Maintain` them

In [132]:
df5 = df.copy()
ndf5 = df5.dropna(thresh =4) # thresh maintain those rows if there is at leas 4 values
ndf5

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VM    NaN     4.0  Mexico     30
4  Cooper    1.0     3.0   China     45

### 6. `Maintain` columns, if there at least 5 data

In [133]:
df6 = df.copy()
ndf6 = df6.dropna(thresh =5, axis = 1) # thresh maintain those rows if there is at leas 4 values
ndf6

  Company  Stars  Weight
0    Ford    1.0     2.0
1    Ford    2.0     4.0
2      VM    NaN     4.0
3     BMW    2.0     2.0
4  Cooper    1.0     3.0
5  Cooper    1.0     NaN

In [134]:
df6.isnull().any() # if we don't want to eliminate and we want to replace it?

Company    False
Stars       True
Weight      True
Origin      True
Length      True
dtype: bool

### 7. Replace missing values with descriptive statistics

For categorical values, when you want to replace the missing value, use mode "descriptive statistics"

Mean (average) is better when there are not outliers.

Median is better when there are outliers.

In [135]:
df.describe ()

          Stars  Weight
count  5.000000     5.0
mean   1.400000     3.0
std    0.547723     1.0
min    1.000000     2.0
25%    1.000000     2.0
50%    1.000000     3.0
75%    2.000000     4.0
max    2.000000     4.0

In [ ]:
df.Stars

In [ ]:
sm = df.Stars.mean()
df['Stars'].fillna(sm, inplace = True) # fill the missing values with stars mean
df.Stars

In [136]:
wm = df.Weight.mean()
df['Weight'].fillna(sm, inplace = True) # fill the missing values with stars mean
df.Weight

/tmp/ipykernel_999/2493616118.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weight'].fillna(sm, inplace = True) # fill the missing values with stars mean

0    2.0
1    4.0
2    4.0
3    2.0
4    3.0
5    1.4
Name: Weight, dtype: float64

### 9. Clean all data

In [137]:
df

  Company  Stars  Weight  Origin Length
0    Ford    1.0     2.0   China     40
1    Ford    2.0     4.0  Mexico     50
2      VM    NaN     4.0  Mexico     30
3     BMW    2.0     2.0    None    NaN
4  Cooper    1.0     3.0   China     45
5  Cooper    1.0     1.4     NaN    NaT

In [138]:
df.isnull().any()

Company    False
Stars       True
Weight     False
Origin      True
Length      True
dtype: bool

In [139]:
df.Origin.describe()

count         4
unique        2
top       China
freq          2
Name: Origin, dtype: object

In [140]:
df.Origin.mode()

0     China
1    Mexico
Name: Origin, dtype: object

In [141]:
Om = df.Origin.mode()[1] # choose mexico. because I can't put both since its a categorical variable
df['Origin'].fillna(Om, inplace = True) # fill the missing values with stars mean
df.Origin

/tmp/ipykernel_999/1947386800.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Origin'].fillna(Om, inplace = True) # fill the missing values with stars mean

0     China
1    Mexico
2    Mexico
3    Mexico
4     China
5    Mexico
Name: Origin, dtype: object

In [142]:
df.Length

0     40
1     50
2     30
3    NaN
4     45
5    NaT
Name: Length, dtype: object

In [143]:
df.Length.describe()

count      4
unique     4
top       40
freq       1
Name: Length, dtype: int64

In [144]:
Lm = df.Length.mean()
df['Length'].fillna(Lm, inplace = True) # fill the missing values with stars mean
df.Length

/tmp/ipykernel_999/1106839727.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Length'].fillna(Lm, inplace = True) # fill the missing values with stars mean

0    40.00
1    50.00
2    30.00
3    41.25
4    45.00
5    41.25
Name: Length, dtype: float64

In [145]:
df

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China   40.00
1    Ford    2.0     4.0  Mexico   50.00
2      VM    NaN     4.0  Mexico   30.00
3     BMW    2.0     2.0  Mexico   41.25
4  Cooper    1.0     3.0   China   45.00
5  Cooper    1.0     1.4  Mexico   41.25

In [146]:
df.isnull().any().sum()

np.int64(1)

As of now , I have a clean. dataset, and i can continue to draw the insights.

### RQ1 :  what is the average Weigh of cars made in Mexico

In [147]:
df

  Company  Stars  Weight  Origin  Length
0    Ford    1.0     2.0   China   40.00
1    Ford    2.0     4.0  Mexico   50.00
2      VM    NaN     4.0  Mexico   30.00
3     BMW    2.0     2.0  Mexico   41.25
4  Cooper    1.0     3.0   China   45.00
5  Cooper    1.0     1.4  Mexico   41.25

In [151]:
origin_info = pd.pivot_table(
    df,
    index = 'Origin', # to know what goes in rows and columns
    aggfunc= 'mean',
    values = 'Weight'
)
origin_info

        Weight
Origin
China     2.50
Mexico    2.85

In [153]:
origin_info.loc['Mexico']
print('Average Weight of cars made in Mexico is \t:', origin_info.loc['Mexico'])

Average Weight of cars made in Mexico is 	: Weight    2.85
Name: Mexico, dtype: float64

### RQ.2 what is the Average Weight of Ford cars made in mexico?

In [157]:
ford_info = pd.pivot_table(
    df,
    index=['Origin', 'Company'], # Group by both Origin and Company
    aggfunc= 'mean',
    values = 'Weight' # Only aggregate the numeric 'Weight' column
)
ford_info

                Weight
Origin Company
China  Cooper      3.0
       Ford        2.0
Mexico BMW         2.0
       Cooper      1.4
       Ford        4.0
       VM          4.0

In [158]:
ford_info.loc['Mexico','Ford']

Weight    4.0
Name: (Mexico, Ford), dtype: float64

In [159]:
ford_info_col = pd.pivot_table(
    df,
    index=['Origin'], # Group by both Origin and Company
    aggfunc= 'mean',
    values = 'Weight', # Only aggregate the numeric 'Weight' column
    columns = 'Company'
)
ford_info_col

Company  BMW  Cooper  Ford   VM
Origin
China    NaN     3.0   2.0  NaN
Mexico   2.0     1.4   4.0  4.0

In [166]:
ford_info_col.loc['Mexico', 'Ford']
print('The average weight for Ford cars in Mexico \t',ford_info_col.loc['Mexico', 'Ford'] )

The average weight for Ford cars in Mexico 	 4.0